include:
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

  - project: tekyn/iac/gitlab-ci-templates
    ref: main
    file: Docker.gitlab-ci.yml

variables:
  AWS_ECR_REPOSITORY: base/php-fpm-nginx

docker:build:builder:
  extends: .docker:build
  variables:
    TARGET: builder
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

docker:publish:builder:
  extends: .docker:build-push
  variables:
    TARGET: builder
    BUILD_ARGS: "--build-arg PHP_VERSION=${CI_COMMIT_TAG}"
  rules:
    - if: $CI_COMMIT_TAG

docker:publish:ci:
  extends: .docker:build-push
  variables:
    TARGET: ci
    BUILD_ARGS: "--build-arg PHP_VERSION=${CI_COMMIT_TAG}"
  rules:
    - if: $CI_COMMIT_TAG

docker:publish:dev:
  extends: .docker:build-push
  variables:
    TARGET: dev
    BUILD_ARGS: "--build-arg PHP_VERSION=${CI_COMMIT_TAG}"
  rules:
    - if: $CI_COMMIT_TAG
